enum Routes {
  RESTAURANTS="Restaurants",
  MAP="Map",
  SETTINGS="Settings",
  SETINGS_MAIN="SETINGS_MAIN",
  RESTAURANTS_LIST="RESTAURANTS_LIST",
  RESTAURANTS_DETAILS="RESTAURANTS_DETAILS",
  SIGN_IN='SIGN_IN',
  SIGN_UP='SIGN_UP',
  HOME="HOME",
  FAVOURITES="FAVOURITES",
}



export default Routes;
